language: ruby
cache: bundler
addons:
  postgresql: "9.6"
rvm:
  - 2.4.2
  - 2.5.1
gemfile:
  - gemfiles/activerecord_5.1.0.gemfile
  - gemfiles/activerecord_5.2.2.gemfile
  - gemfiles/activerecord_6.0.0.gemfile
env:
  - DB=postgres

matrix:
  fast_finish: true
  exclude:
  - rvm: 2.2.6
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: 2.3.5
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: 2.4.2
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: 2.7.0
    gemfile: gemfiles/activerecord_4.2.0.gemfile
  - rvm: jruby-9.1.17.0
    gemfile: gemfiles/activerecord_5.0.2.gemfile
  - rvm: jruby-9.1.17.0
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  - rvm: jruby-9.2.11.0
    gemfile: gemfiles/activerecord_5.0.2.gemfile
  - rvm: jruby-9.2.11.0
    gemfile: gemfiles/activerecord_6.0.0.gemfile
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

before_install:
  - rvm get stable
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake
